/**
 * StationImagesService
 * 
 * Service for accessing station images from Wikimedia Commons.
 * Provides methods to get images for stations and manage image metadata.
 */

import type { Station } from '@/types/metro';
import type { StationImage, StationImageMap } from '@/types/station-images';

// Import generated image data (will be auto-generated by fetch script)
// @ts-ignore - This file will be generated
import stationImagesData from '@/data/station-images';

class StationImagesService {
  private static instance: StationImagesService;
  private images: StationImageMap;
  private imageCache: Map<string, StationImage[]> = new Map();

  private constructor() {
    // Initialize with empty data, will be populated by fetch script
    this.images = stationImagesData || {};
    this.buildCache();
  }

  /**
   * Get singleton instance
   */
  public static getInstance(): StationImagesService {
    if (!StationImagesService.instance) {
      StationImagesService.instance = new StationImagesService();
    }
    return StationImagesService.instance;
  }

  /**
   * Build cache for faster lookups
   */
  private buildCache(): void {
    this.imageCache.clear();
    for (const [stationId, images] of Object.entries(this.images)) {
      this.imageCache.set(stationId, images);
    }
  }

  /**
   * Get images for a station
   */
  public getStationImages(stationId: string): StationImage[] {
    return this.imageCache.get(stationId) || [];
  }

  /**
   * Get primary image for a station
   */
  public getPrimaryImage(stationId: string): StationImage | undefined {
    const images = this.getStationImages(stationId);
    return images.find(img => img.isPrimary) || images[0];
  }

  /**
   * Check if a station has images
   */
  public hasImages(stationId: string): boolean {
    return this.imageCache.has(stationId) && this.getStationImages(stationId).length > 0;
  }

  /**
   * Get all stations with images
   */
  public getStationsWithImages(): string[] {
    return Array.from(this.imageCache.keys());
  }

  /**
   * Get statistics about images
   */
  public getStats() {
    const totalStations = Object.keys(this.images).length;
    const stationsWithImages = this.getStationsWithImages().length;
    const totalImages = Object.values(this.images).reduce((sum, images) => sum + images.length, 0);
    
    return {
      totalStations,
      stationsWithImages,
      stationsWithoutImages: totalStations - stationsWithImages,
      totalImages,
      coverage: totalStations > 0 ? (stationsWithImages / totalStations) * 100 : 0
    };
  }

  /**
   * Get image by station (convenience method)
   */
  public getImageForStation(station: Station): StationImage | undefined {
    return this.getPrimaryImage(station.id);
  }

  /**
   * Get all images (for credits page)
   */
  public getAllImages(): StationImage[] {
    return Object.values(this.images).flat();
  }

  /**
   * Get images grouped by license (for credits page)
   */
  public getImagesByLicense(): Record<string, StationImage[]> {
    const byLicense: Record<string, StationImage[]> = {};
    
    for (const images of Object.values(this.images)) {
      for (const image of images) {
        const license = image.metadata.license;
        if (!byLicense[license]) {
          byLicense[license] = [];
        }
        byLicense[license].push(image);
      }
    }
    
    return byLicense;
  }

  /**
   * Get images grouped by author (for credits page)
   */
  public getImagesByAuthor(): Record<string, StationImage[]> {
    const byAuthor: Record<string, StationImage[]> = {};
    
    for (const images of Object.values(this.images)) {
      for (const image of images) {
        const author = image.metadata.author || 'Unknown';
        if (!byAuthor[author]) {
          byAuthor[author] = [];
        }
        byAuthor[author].push(image);
      }
    }
    
    return byAuthor;
  }

  /**
   * Update images (for development/testing)
   */
  public updateImages(newImages: StationImageMap): void {
    this.images = newImages;
    this.buildCache();
  }

  /**
   * Clear all images (for testing)
   */
  public clear(): void {
    this.images = {};
    this.imageCache.clear();
  }
}

// Export singleton instance
export const stationImagesService = StationImagesService.getInstance();